### ISSUE TITLE
Unit tests for fitting methods

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Autostronomy/AstroPhot#12]
The fitting methods currently have no unit tests, these should be added to check functionality.

**Comment by ranbir7** [comment]
shall I add the tests in the same code files ?or I have to make separate?

**Comment by ConnorStoneAstro** [comment]
There is a separate `tests` directory where the tests are written. So any new tests should be written there. And the tests are run with `pytest`

**Comment by ranbir7** [comment]
okay I got it!👍

**Comment by ConnorStoneAstro** [comment]
Most fitting methods now have basic unit tests. More can come, but this issue is no longer needed.
