### ISSUE TITLE
plots.model_images doesn't actually use the passed in `window` when plotting

### ISSUE THREAD

**Issue by wmwv** [Autostronomy/AstroPhot#122]
**Describe the bug**
ap.plots.model_images doesn't use the passed in `window` when plotting

https://github.com/Autostronomy/AstroPhot/blob/726db052777ac35c090d4b2045bd296719aff7e9/astrophot/plots/image.py#L100

I expected the test_model_window function to test this but it doesn't:
https://github.com/Autostronomy/AstroPhot/blob/726db052777ac35c090d4b2045bd296719aff7e9/tests/test_plots.py#L81

I appreciate that testing plotting is tedious and touchy to get right.  E.g., you have to pin matplotlib to get the exact same PNG output, and that's only so much fun.

In practice, I should just pass the window when defining the model.  But as long as `model_images` accepts a `window` keyword it should work :)

**To Reproduce**
Pardon, I don't have a minimally-reproduciable example.  But here's an example of the cell where `residual_image` works and shows just the window region, but `model_image` shows the entire image instead of just the window.

```
fig, ax = plt.subplots(1, 2, figsize = (16,6))
ap.plots.model_image(fig, ax[0], model_0, window=window0)
ap.plots.residual_image(fig, ax[1], model_0, window=window0)
plt.show()
```

**Comment by ConnorStoneAstro** [comment]
Oh, that's quite a goof on my part! I can fix that fairly easily. Good catch!
