### ISSUE TITLE
Make print(model.parameters) generate the expected output

### ISSUE THREAD

**Issue by wmwv** [Autostronomy/AstroPhot#128]
**Is your feature request related to a problem? Please describe.**

The following example from GettingSarted.ipynb seems like something a user will want to do often:
```
for P in model.parameters:
    print(f"parameter {P.name} is: {P.value.detach().cpu().tolist()} +- {P.uncertainty.detach().cpu().tolist()}")
```
and it seems tedious and error-prone to type that out every time.

**Describe the solution you'd like**

Would it be possible to update the __str__ for a `parameters` object to generate this string itself?  E.g., so I can just type

```
print(model.parameters)
```
and get the same output as the explicitly for loop above?

**Comment by wmwv** [comment]
`print(model)` gives me the YAML string which takes many more lines and takes longer for me to parse.

**Comment by ConnorStoneAstro** [comment]
Yeah, that makes sense. Maybe the full YAML string could be for the repr, while the more concise system above is appropriate for print.

**Comment by wmwv** [comment]
And now that I'm thinking about it, one might also want a convenience function that just prints the independent parameters.
