### ISSUE TITLE
target_image expects a list or targets, but only one window.

### ISSUE THREAD

**Issue by wmwv** [Autostronomy/AstroPhot#142]
**Describe the bug**
`astrophot.plots.image.target_list` doesn't offer an easy way to pass a list of windows.  The `window` argument is either one `Window` or `None`.  If you pass it a list of windows, it fails.

I found this confusing.  I expected to be able to pass a list of target.image_list and a list of `Window` objects and that it would just work.

**To Reproduce**

**Expected behavior**

-            target_image(fig, ax[i], target.image_list[i], window=window, **kwargs)
+            wi = None
+            if window is not None:
+                if hasattr(window, "__iter__"):
+                    wi = window[i]
+                else:
+                    wi = window
+            target_image(fig, ax[i], target.image_list[i], window=wi, **kwargs)

is sort of a fix.

**Comment by ConnorStoneAstro** [comment]
Ah the intention is for you to pass a Window_List object. But there should be an option to just pass a list of windows and it could construct the Window_List behind the scenes

**Comment by wmwv** [comment]
Hmmm... passing a Window_List also doesn't work. 

When I look at the code, I'm not sure I see how it would:
```
    if isinstance(target, Image_List):
        for i in range(len(target.image_list)):
            target_image(fig, ax[i], target.image_list[i], window=window, **kwargs)
        return fig, ax
```
https://github.com/Autostronomy/AstroPhot/blob/6081c69558144131b505c19ccdfa4d03ad09e1a4/astrophot/plots/image.py#L42

**Comment by ConnorStoneAstro** [comment]
My apologies, yes, there never was an option to update the Target_List window. I think I've added the functionality in #144 let me know if this is what you were looking for!
