### ISSUE TITLE
Bug report: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by Mebiusbear** [Autostronomy/AstroPhot#149]
**This bug appears when I'm running ap.fit.LM(model2, verbose = 1).fit()**

In the preceding two lines of code, the variable pixel_shape is explicitly moved from a tensor to CPU using .cpu(). Consequently, attempting to use window.pixel_shape in the subsequent lines results in an error.

https://github.com/Autostronomy/AstroPhot/blob/e816201d5149eead74d195bcf6832b31fdc8dff3/astrophot/models/model_object.py#L512C44-L512C44

**Comment by ConnorStoneAstro** [comment]
Hi @Mebiusbear , thanks for spotting this! Could you send a screenshot/trace of the full error? I'll make sure this is fixed today.

**Comment by ConnorStoneAstro** [comment]
Please see PR #150 and let me know if this would fix the problem. I'm going to run some tests on GPU, but it would be nice to hear if this addresses your problem in particular :)

**Comment by ConnorStoneAstro** [comment]
Closed by #150
