### ISSUE TITLE
output best-fit model(s) in .fits format

### ISSUE THREAD

**Issue by eiani** [Autostronomy/AstroPhot#195]
Good morning, I was wondering if there is an easy way to have the best-fit models derived with astrophot in a .fits format (as with Galfit). It would be of great help to easily save the best-fit model(s) in a fits file with an extension for each fitted galaxy/component and a final one with the residuals. Would it be possible to add such a feature?

**Comment by ConnorStoneAstro** [comment]
Hi @eiani , good question! that is already an available feature. For any AstroPhot image object you can call `image.save("name.fits")` and the image will be saved in fits format. So to save the final model image you can call `model().save("model.fits")` to save the residual image you can call `(target - model()).save("residual.fits")` and you should get the images you're looking for. There are more details in the tutorial Jupyter notebooks here: https://astrophot.readthedocs.io/en/latest/tutorials/GettingStarted.html
