### ISSUE TITLE
Update to numpy 2.0

### ISSUE THREAD

**Issue by wmwv** [Autostronomy/AstroPhot#214]
**Describe the bug** A clear and concise description of what the bug is.

numpy 2.0 has a variety of changes, the vast majority of which are automatable.

https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide

The automatic tool `ruff` says the only two needed changes are amusingly about getting the type right for ignoring numpy `VisibleDeprecationWarning` :)

```
[Calm-4 AstroPhot] ruff check astrophot --select NPY201
astrophot/utils/decorators.py:21:52: NPY201 [*] `np.VisibleDeprecationWarning` will be removed in NumPy 2.0. Use `numpy.exceptions.VisibleDeprecationWarning` instead.
   |
19 |     def wrapped(*args, **kwargs):
20 |         old_settings = np.seterr(all="ignore")
21 |         warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NPY201
22 |         result = func(*args, **kwargs)
23 |         np.seterr(**old_settings)
   |
   = help: Replace with `numpy.exceptions.VisibleDeprecationWarning`

astrophot/utils/decorators.py:24:53: NPY201 [*] `np.VisibleDeprecationWarning` will be removed in NumPy 2.0. Use `numpy.exceptions.VisibleDeprecationWarning` instead.
   |
22 |         result = func(*args, **kwargs)
23 |         np.seterr(**old_settings)
24 |         warnings.filterwarnings("default", category=np.VisibleDeprecationWarning)
   |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NPY201
25 |         return result
   |
   = help: Replace with `numpy.exceptions.VisibleDeprecationWarning`

Found 2 errors.
[*] 2 fixable with the `--fix` option.
```

**Comment by ConnorStoneAstro** [comment]
Good catch! I was just starting to look into updating some stuff like this. I have a PR for testing on python 3.11 and 3.12 in the works. Would you like to put a PR forward for this, or should I?

**Comment by wmwv** [comment]
I'm working on one.

**Comment by wmwv** [comment]
Hmmm, I think the code within `astrophot` is fine.  But tracing down ABI compatibility is going to be the frustration for the user.  E.g., right now I'm failing to get a version of `pytorch` that's compiled right.

**Comment by ConnorStoneAstro** [comment]
Hmmm, so the `numpy.exceptions.VisibleDeprecationWarning` fix isn't an issue, but pytorch is incompatible with numpy 2.0? Perhaps there are some requirements in my `requirements.txt` file that need to be updated?

**Comment by wmwv** [comment]
pytorch says it's compatible with numpy 2.0.  The problem is that numpy 2.0 is an ABI-breaking changing, so modules can be compiled for numpy<2 or numpy >=2, but not both at the same time.  And comvincing the modules they want to do that (and grabbing the the right pip wheel) is unobvious to debug when it doesn't work.

**Comment by ConnorStoneAstro** [comment]
Hmmm, I'm not especially proficient with packaging and version management. Perhaps for now we make the change for the numpy depreciation warning, but also require the numpy version to be strictly less than 2. We can wait until numpy 2.0 compatibility is more common, then switch fully. Or am I not understanding the problem?

**Comment by wmwv** [comment]
I actually think the pytorch issue is MacOS specific.  Updated pytorch 2.3 wheels aren't built yet, and pytorch 2.3 is the first to be numpy 2.0 compatible.

So I think my suggestion would be to make the changes in the branch, then test on a platform with numpy 2.0 (I'll build on a linux machine tomorrow in a fresh environment).  If that works, then we can go ahead and just add these changes.  And then add a note about needing pytorch 2.3 and that that's not available yet easily for MacOS.

I don't like putting in a limit, because we don't really have a test for it that we run to resolve?  Or, to put another way, we have lots of tests that will all fail on MacOS until pytorch is right.

**Comment by ConnorStoneAstro** [comment]
Ok, a warning next to the install instructions seems reasonable. I guess on import we could also check that if the numpy version is >= 2 then pytorch must be >=2.3 or we throw a warning

**Comment by wmwv** [comment]
`astrophot` will already fail on import when it in turns imports `pytorch`:

```
>>> import astrophot

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/astrophot/__init__.py", line 3, in <module>
    import torch
  File "/usr/local/lib/python3.11/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/usr/local/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/usr/local/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
>>>
```

**Comment by ConnorStoneAstro** [comment]
Great! So we don't need any special logic to handle this. It will just be a pain for some people to get a configuration that is compatible with numpy2.0

**Comment by ConnorStoneAstro** [comment]
Hmmm, I think the numpy 2.0 fix for the depreciation warning might already be implemented: https://github.com/Autostronomy/AstroPhot/blob/7a44cb6e7357c490809b0e8fec5f52e9191a3a80/astrophot/utils/decorators.py#L21

Perhaps I did this a while ago and forgot? I just saw it as I was pushing the latest dev release

**Comment by wmwv** [comment]
Agreed.  Closing.
