### ISSUE TITLE
PSF model basics tutorial issue 

### ISSUE THREAD

**Issue by sanast** [Autostronomy/AstroPhot#221]
Hi 

I tried to run this tutorial   "(https://astrophot.readthedocs.io/en/latest/tutorials/BasicPSFModels.html) "  but got these  error messages. Just wondering how to fix this.  (I just downloaded the notebook and ran in my machine )

AttributeError: 'PSF_Image' object has no attribute 'normalize.'

module 'astrophot.plots' has no attribute 'psf_image'

**Comment by ConnorStoneAstro** [comment]
Hmm, that is a strange error to get. I wonder if you are using the latest version of AstrPhot? Could you check the version with something like ap.__version__ ? It should be 0.16.5 but you may have ended up with an older version if you aren't using an updated Python version.

**Comment by sanast** [comment]
Yes. Thank you. I had the older version. I had a reinstallation with the new version, and it works now.
