### ISSUE TITLE
Metropolis Adjusted Langevin Algorithm

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Autostronomy/AstroPhot#3]
The MALA has been crudely implemented, needs to be debugged and tested to get it up and running

**Comment by ranbir7** [comment]
the algorithm is required for image processing?

**Comment by ConnorStoneAstro** [comment]
For scientific purposes, this algorithm allows the user to fit image while also getting very realistic measurements of the uncertainty in the fit

**Comment by ranbir7** [comment]
okay okay...I was just trying to get into this😄

**Comment by ConnorStoneAstro** [comment]
This is a tricky one. If you are interested, I suggest you learn about MCMC sampling methods first. The MALA is a higher level version that uses gradients of the log probability instead of directly accessing the probability.

**Comment by ranbir7** [comment]
okay lemme check abt it....
