### ISSUE TITLE
Linting with Black

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Autostronomy/AstroPhot#61]
**describe the content in question**

The code throughout should be linted for better readability and to catch tricky errors. An effective linter is `black` ([see here](https://black.readthedocs.io/en/stable/)) which should be able to handle the relevant use cases for AutoProf.

**example use case**

Anyone reading the code will benefit from stronger code standards with linting.

**brief outline of updated documentation**

This is less documentation and more code quality, so the form of the change will be the structure of the code

**Comment by ranbir7** [comment]
Excited about this
cuz I have been using it without even knowing it !

**Comment by ranbir7** [comment]
U wont believe I ran it with the fit dir files 
and just updated lm.py & base.py file
most of them are formatted according to _black!._

**Comment by ranbir7** [comment]
Just like Black there are tools for TyepHints.
Pyright, Typeguard, Pyannotate are the tools
shall We start using them?

**Comment by ConnorStoneAstro** [comment]
These look like really powerful tools! I don't think they need to be added as a formal requirement like black formatting. You can just use them to help add type hints faster. Looking at how they work it will be necessary to make small modifications after they run, but mostly they should speed up the process quite a bit!
